//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.TcpEndpoint
{
    public class RosUnityConnectionParam : Message
    {
        public const string RosMessageName = "tcp_endpoint/RosUnityConnectionParam";

        public bool keepConnectionOpen;

        public RosUnityConnectionParam()
        {
            this.keepConnectionOpen = false;
        }

        public RosUnityConnectionParam(bool keepConnectionOpen)
        {
            this.keepConnectionOpen = keepConnectionOpen;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.keepConnectionOpen));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.keepConnectionOpen = BitConverter.ToBoolean(data, offset);
            offset += 1;

            return offset;
        }

    }
}
